import type { DataSnapshot } from '../types/domain'

const now = new Date()
const iso = (offsetDays: number) => {
  const date = new Date(now)
  date.setDate(date.getDate() + offsetDays)
  return date.toISOString().slice(0, 10)
}

export const seedSnapshot: DataSnapshot = {
  profiles: [
    {
      id: 'profile-owner',
      fullName: 'R Pang',
      email: 'owner@kanikan.local',
      role: 'owner',
      language: 'id',
      telegramId: '123456789',
    },
    {
      id: 'profile-member',
      fullName: 'Farm Operator',
      email: 'member@kanikan.local',
      role: 'member',
      language: 'en',
      telegramId: '987654321',
    },
  ],
  ponds: [
    { id: 'pond-1', name: 'Bucket 1', type: 'Ember', capacity: 80, isActive: true, description: 'Lele growout cepat.' },
    { id: 'pond-2', name: 'Bucket 2', type: 'Ember', capacity: 100, isActive: true, description: 'Cycle tanpa target.' },
    { id: 'pond-3', name: 'Kolam 1', type: 'Kolam', capacity: 3000, isActive: true, description: 'Nila aktif.' },
    { id: 'pond-4', name: 'Kolam 2', type: 'Kolam', capacity: 3500, isActive: true, description: 'Patin hasil transfer.' },
    { id: 'pond-5', name: 'Quarantine 1', type: 'Bak', capacity: 500, isActive: false, description: 'Cadangan.' },
  ],
  cycles: [
    {
      id: 'cycle-101',
      name: 'Cycle 101',
      unitId: 'pond-1',
      fishType: 'Lele',
      dateStart: iso(-75),
      dateEnd: null,
      initialStock: 1200,
      avgSeedWeightG: 5,
      targetWeightG: 180,
      capitalRp: 2400000,
      description: 'Fast growth cycle.',
    },
    {
      id: 'cycle-102',
      name: 'Cycle 102',
      unitId: 'pond-2',
      fishType: 'Lele',
      dateStart: iso(-28),
      dateEnd: null,
      initialStock: 800,
      avgSeedWeightG: 4,
      targetWeightG: null,
      capitalRp: 1500000,
      description: 'Target weight belum diisi.',
    },
    {
      id: 'cycle-103',
      name: 'Cycle 103',
      unitId: 'pond-3',
      fishType: 'Nila',
      dateStart: iso(-54),
      dateEnd: null,
      initialStock: 2000,
      avgSeedWeightG: 8,
      targetWeightG: 250,
      capitalRp: 3600000,
      description: 'Nila aktif.',
    },
    {
      id: 'cycle-105',
      name: 'Cycle 105',
      unitId: 'pond-4',
      fishType: 'Patin',
      dateStart: iso(-10),
      dateEnd: null,
      initialStock: 585,
      avgSeedWeightG: 190,
      targetWeightG: 320,
      capitalRp: 1200000,
      description: 'Transfer continuation dari Bucket 3.',
    },
  ],
  dailyLogs: [
    {
      id: 'log-1',
      date: iso(-1),
      unitId: 'pond-1',
      cycleId: 'cycle-101',
      fishType: 'Lele',
      feedG: 3200,
      event: 'Ikan aktif',
      action: 'Tambah aerasi',
      description: 'Air agak keruh, ikan aktif.',
      sampleWeightG: 145,
      sampleCount: 10,
      createdBy: 'profile-owner',
    },
    {
      id: 'log-2',
      date: iso(0),
      unitId: 'pond-2',
      cycleId: 'cycle-102',
      fishType: 'Lele',
      feedG: 1800,
      event: 'Hujan deras',
      action: 'Cek air sore',
      description: 'Hujan deras, air keruh.',
      sampleWeightG: 42,
      sampleCount: 10,
      createdBy: 'profile-member',
    },
    {
      id: 'log-3',
      date: iso(-1),
      unitId: 'pond-3',
      cycleId: 'cycle-103',
      fishType: 'Nila',
      feedG: 5200,
      event: 'Stabil',
      action: 'Normal feed',
      description: 'Kondisi stabil.',
      sampleWeightG: 130,
      sampleCount: 10,
      createdBy: 'profile-owner',
    },
  ],
  stockMovements: [
    { id: 'mv-1', date: iso(-75), unitId: 'pond-1', cycleId: 'cycle-101', fishType: 'Lele', movementType: 'stock_in', count: 1200, weightKg: null, description: 'Stock in awal', meta: {}, sourceTable: 'fish_inventory', sourceRowId: 'fi-1', createdBy: 'profile-owner', createdAt: `${iso(-75)}T08:00:00Z` },
    { id: 'mv-2', date: iso(-50), unitId: 'pond-1', cycleId: 'cycle-101', fishType: 'Lele', movementType: 'died', count: 35, weightKg: null, description: 'Kematian awal', meta: {}, sourceTable: 'fish_inventory', sourceRowId: 'fi-2', createdBy: 'profile-owner', createdAt: `${iso(-50)}T08:00:00Z` },
    { id: 'mv-3', date: iso(-14), unitId: 'pond-1', cycleId: 'cycle-101', fishType: 'Lele', movementType: 'sold', count: 180, weightKg: 5.8, description: 'Batch 1', meta: {}, sourceTable: 'penjualan', sourceRowId: 'sale-1', createdBy: 'profile-owner', createdAt: `${iso(-14)}T08:00:00Z` },
    { id: 'mv-4', date: iso(-2), unitId: 'pond-1', cycleId: 'cycle-101', fishType: 'Lele', movementType: 'sold', count: 240, weightKg: 7.4, description: 'Batch 2', meta: {}, sourceTable: 'penjualan', sourceRowId: 'sale-2', createdBy: 'profile-owner', createdAt: `${iso(-2)}T08:00:00Z` },
    { id: 'mv-5', date: iso(-28), unitId: 'pond-2', cycleId: 'cycle-102', fishType: 'Lele', movementType: 'stock_in', count: 800, weightKg: null, description: 'Stock in', meta: {}, sourceTable: 'fish_inventory', sourceRowId: 'fi-3', createdBy: 'profile-member', createdAt: `${iso(-28)}T08:00:00Z` },
    { id: 'mv-6', date: iso(-7), unitId: 'pond-2', cycleId: 'cycle-102', fishType: 'Lele', movementType: 'died', count: 22, weightKg: null, description: 'Hujan', meta: {}, sourceTable: 'fish_inventory', sourceRowId: 'fi-4', createdBy: 'profile-member', createdAt: `${iso(-7)}T08:00:00Z` },
    { id: 'mv-7', date: iso(-54), unitId: 'pond-3', cycleId: 'cycle-103', fishType: 'Nila', movementType: 'stock_in', count: 2000, weightKg: null, description: 'Stock in', meta: {}, sourceTable: 'fish_inventory', sourceRowId: 'fi-5', createdBy: 'profile-owner', createdAt: `${iso(-54)}T08:00:00Z` },
    { id: 'mv-8', date: iso(-12), unitId: 'pond-3', cycleId: 'cycle-103', fishType: 'Nila', movementType: 'died', count: 40, weightKg: null, description: 'Kematian ringan', meta: {}, sourceTable: 'fish_inventory', sourceRowId: 'fi-6', createdBy: 'profile-owner', createdAt: `${iso(-12)}T08:00:00Z` },
    { id: 'mv-9', date: iso(-3), unitId: 'pond-3', cycleId: 'cycle-103', fishType: 'Nila', movementType: 'sold', count: 350, weightKg: 25, description: 'Panen parsial', meta: {}, sourceTable: 'penjualan', sourceRowId: 'sale-3', createdBy: 'profile-owner', createdAt: `${iso(-3)}T08:00:00Z` },
    { id: 'mv-10', date: iso(-10), unitId: 'pond-4', cycleId: 'cycle-105', fishType: 'Patin', movementType: 'transfer_in', count: 585, weightKg: null, description: 'Transfer in dari Bucket 3', meta: { fromUnit: 'Bucket 3' }, sourceTable: 'bot_transfer', sourceRowId: 'transfer-1', createdBy: 'profile-owner', createdAt: `${iso(-10)}T08:00:00Z` },
    { id: 'mv-11', date: iso(-2), unitId: 'pond-4', cycleId: 'cycle-105', fishType: 'Patin', movementType: 'died', count: 8, weightKg: null, description: 'Stres pasca transfer', meta: {}, sourceTable: 'fish_inventory', sourceRowId: 'fi-7', createdBy: 'profile-owner', createdAt: `${iso(-2)}T08:00:00Z` },
  ],
  sales: [
    { id: 'sale-1', date: iso(-14), unitId: 'pond-1', cycleId: 'cycle-101', fishType: 'Lele', weightKg: 5.8, pricePerKg: 22000, totalRp: 127600, buyer: 'Buyer A', soldCount: 180, soldCountSource: 'manual', avgWeightUsedG: 145, createdBy: 'profile-owner', stockReduced: true },
    { id: 'sale-2', date: iso(-2), unitId: 'pond-1', cycleId: 'cycle-101', fishType: 'Lele', weightKg: 7.4, pricePerKg: 22500, totalRp: 166500, buyer: 'Buyer B', soldCount: 240, soldCountSource: 'estimated', avgWeightUsedG: 155, createdBy: 'profile-owner', stockReduced: true },
    { id: 'sale-3', date: iso(-3), unitId: 'pond-3', cycleId: 'cycle-103', fishType: 'Nila', weightKg: 25, pricePerKg: 28000, totalRp: 700000, buyer: 'Buyer C', soldCount: null, soldCountSource: null, avgWeightUsedG: null, createdBy: 'profile-owner', stockReduced: false },
  ],
  cashEntries: [
    { id: 'cash-1', date: iso(-14), type: 'Masuk', categoryId: 'cash-cat-sales', description: 'Penjualan Batch 1 | Note: Buyer A', cycleId: 'cycle-101', amountRp: 127600, createdBy: 'profile-owner', sourceSaleId: 'sale-1' },
    { id: 'cash-2', date: iso(-2), type: 'Masuk', categoryId: 'cash-cat-sales', description: 'Penjualan Batch 2 | Note: Buyer B', cycleId: 'cycle-101', amountRp: 166500, createdBy: 'profile-owner', sourceSaleId: 'sale-2' },
    { id: 'cash-3', date: iso(-3), type: 'Masuk', categoryId: 'cash-cat-sales', description: 'Penjualan Nila | Note: Buyer C', cycleId: 'cycle-103', amountRp: 700000, createdBy: 'profile-owner', sourceSaleId: 'sale-3' },
    { id: 'cash-4', date: iso(-8), type: 'Keluar', categoryId: 'cash-cat-feed', description: 'Beli pakan mingguan | Note: Pelet 781', cycleId: 'cycle-101', amountRp: 230000, createdBy: 'profile-owner', sourceSaleId: null },
    { id: 'cash-5', date: iso(-5), type: 'Keluar', categoryId: 'cash-cat-operational', description: 'Transport air', cycleId: null, amountRp: 95000, createdBy: 'profile-owner', sourceSaleId: null },
  ],
  kasCategories: [
    { id: 'cash-cat-sales', type: 'Masuk', name: 'Penjualan', sortOrder: 1 },
    { id: 'cash-cat-capital', type: 'Masuk', name: 'Modal', sortOrder: 2 },
    { id: 'cash-cat-income-other', type: 'Masuk', name: 'Lainnya', sortOrder: 999 },
    { id: 'cash-cat-feed', type: 'Keluar', name: 'Pakan', sortOrder: 1 },
    { id: 'cash-cat-operational', type: 'Keluar', name: 'Operasional', sortOrder: 2 },
    { id: 'cash-cat-medicine', type: 'Keluar', name: 'Obat/Suplemen', sortOrder: 3 },
    { id: 'cash-cat-outcome-other', type: 'Keluar', name: 'Lainnya', sortOrder: 999 },
  ],
}
